"""phase2a native outcome foundation and guardrails

Native survivorship-clean outcome foundation on the permanent ``security_id``
(docs/PHASE2_DESIGN.md, PHASE3_IDENTITY_MIGRATION.md — Phase 2A). Adds the
first-class identity bridge, native price/market/return/forward-outcome tables,
benchmark returns, terminal-outcome handling, execution-level experiment
provenance, and the two-track parity ledgers. Extends the ingestion_runs
run_type check to allow the Phase-2A run types (the update_run_type / phase1
precedent). Nothing here touches production scoring; it is purely additive.

Note: alembic's autogenerated draft additionally proposed dropping the dynamic
feature_store_* yearly partitions (present in the DB, absent from ORM metadata
by design) and an ALTER of the run_type enum column. Those were removed by hand
and the run_type change re-expressed as a raw-SQL CHECK swap, matching the
phase1 migration.

Revision ID: 710af4aa92d0
Revises: fba564e9cd38
Create Date: 2026-07-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "710af4aa92d0"
down_revision: str | None = "fba564e9cd38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Full run_type vocabulary AFTER this migration; the last five are new here.
_RUN_TYPES = (
    "prices",
    "macro",
    "fundamentals",
    "earnings",
    "features",
    "snapshots",
    "portfolio_import",
    "update",
    "securities",
    "universe",
    "bridge",
    "research_prices",
    "research_outcomes",
    "research_snapshot",
    "experiment",
)
_NEW_RUN_TYPES = (
    "bridge",
    "research_prices",
    "research_outcomes",
    "research_snapshot",
    "experiment",
)


def _run_type_check(values: tuple[str, ...]) -> str:
    return "run_type IN (" + ", ".join(f"'{v}'" for v in values) + ")"


def _identity_world(name: str = "identity_world_e") -> sa.Enum:
    return sa.Enum(
        "legacy_instrument",
        "native_security",
        name=name,
        native_enum=False,
        create_constraint=True,
    )


def upgrade() -> None:
    op.create_table(
        "instrument_security_map",
        sa.Column("map_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("mapping_reason", sa.Text(), nullable=True),
        sa.Column(
            "mapping_method",
            sa.Enum(
                "exact_source_id",
                "permanent_identifier",
                "manual_override",
                "pit_ticker",
                name="mapping_method_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "quarantined",
                "superseded",
                name="mapping_status_e",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_record_id", sa.Text(), nullable=True),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_instrument_security_map_ism_confidence_unit"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from <= valid_to",
            name=op.f("ck_instrument_security_map_ism_interval_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_instrument_security_map_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_instrument_security_map_instrument_id_instruments"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_instrument_security_map_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("map_id", name=op.f("pk_instrument_security_map")),
    )
    op.create_index(
        "ix_ism_instrument",
        "instrument_security_map",
        ["instrument_id", "valid_from"],
        unique=False,
    )
    op.create_index(
        "ix_ism_security", "instrument_security_map", ["security_id", "valid_from"], unique=False
    )

    op.create_table(
        "security_price_daily",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("adjusted_close", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("total_return_factor", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("split_factor", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("dividend_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("currency", sa.Text(), server_default="USD", nullable=False),
        sa.Column("exchange", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_record_id", sa.Text(), nullable=True),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "close IS NULL OR close >= 0", name=op.f("ck_security_price_daily_spd_close_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_security_price_daily_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_security_price_daily_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_price_daily")),
        sa.UniqueConstraint(
            "security_id", "trade_date", "source", "data_version", name="uq_spd_natural"
        ),
    )
    op.create_index("ix_spd_date", "security_price_daily", ["trade_date"], unique=False)

    op.create_table(
        "security_market_snapshot",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("shares_outstanding", sa.BigInteger(), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("average_dollar_volume", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("exchange", sa.Text(), nullable=True),
        sa.Column(
            "security_type",
            sa.Enum(
                "common",
                "adr",
                "etf",
                "preferred",
                "warrant",
                "right",
                "unit",
                "closed_end_fund",
                "reit",
                "other",
                name="security_type_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "market_cap IS NULL OR market_cap >= 0",
            name=op.f("ck_security_market_snapshot_sms_mktcap_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_security_market_snapshot_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_security_market_snapshot_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_market_snapshot")),
        sa.UniqueConstraint(
            "security_id", "snapshot_date", "source", "data_version", name="uq_sms_natural"
        ),
    )
    op.create_index("ix_sms_date", "security_market_snapshot", ["snapshot_date"], unique=False)

    op.create_table(
        "benchmark_return_daily",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("benchmark_key", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("total_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_benchmark_return_daily_ingestion_run_id_ingestion_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_return_daily")),
        sa.UniqueConstraint(
            "benchmark_key", "trade_date", "source", "data_version", name="uq_brd_natural"
        ),
    )
    op.create_index("ix_brd_date", "benchmark_return_daily", ["trade_date"], unique=False)

    op.create_table(
        "security_return_daily",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("price_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("dividend_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("delisting_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("total_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column(
            "return_status",
            sa.Enum(
                "normal",
                "corporate_action",
                "delisting",
                "terminal",
                "missing",
                "unresolved",
                name="return_status_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.Column("calculation_version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_security_return_daily_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_security_return_daily_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_return_daily")),
        sa.UniqueConstraint(
            "security_id",
            "trade_date",
            "source",
            "data_version",
            "calculation_version",
            name="uq_srd_natural",
        ),
    )
    op.create_index("ix_srd_date", "security_return_daily", ["trade_date"], unique=False)

    op.create_table(
        "terminal_outcome",
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column(
            "rule",
            sa.Enum(
                "cash_acquisition",
                "stock_acquisition",
                "merger",
                "bankruptcy",
                "liquidation",
                "stopped_trading",
                "vendor_delisting_return",
                "unknown",
                name="terminal_rule_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("terminal_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("terminal_value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("cash_consideration", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("successor_security_id", sa.BigInteger(), nullable=True),
        sa.Column("resolved", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "dq_status",
            sa.Enum(
                "open",
                "accepted",
                "resolved",
                name="issue_status_e",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.Column("calculation_version", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_terminal_outcome_terminal_confidence_unit"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_terminal_outcome_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_terminal_outcome_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_terminal_outcome")),
    )

    op.create_table(
        "research_dataset_snapshot",
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_name", sa.Text(), nullable=False),
        sa.Column("snapshot_version", sa.Integer(), nullable=False),
        sa.Column("universe_definition_id", sa.BigInteger(), nullable=True),
        sa.Column("universe_version", sa.Text(), nullable=True),
        sa.Column("identity_world", _identity_world(), nullable=False),
        sa.Column("feature_world", _identity_world("feature_world_e"), nullable=True),
        sa.Column("outcome_world", _identity_world("outcome_world_e"), nullable=False),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.Column("code_sha", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("security_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("date_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot_checksum", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "frozen",
                name="snapshot_status_e",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["universe_definition_id"],
            ["universe_definition.universe_definition_id"],
            name=op.f("fk_research_dataset_snapshot_universe_definition_id_universe_definition"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_research_dataset_snapshot")),
        sa.UniqueConstraint("snapshot_name", "snapshot_version", name="uq_rds_name_ver"),
    )

    op.create_table(
        "forward_return",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("horizon", sa.Text(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("absolute_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("benchmark_relative_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("sector_relative_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("residual_return", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("terminal_event_flag", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("delisting_in_window_flag", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "outcome_status",
            sa.Enum(
                "normal",
                "delisted_in_window",
                "terminated",
                "truncated",
                "unresolved",
                "no_entry_price",
                name="outcome_status_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "identity_world", _identity_world(), server_default="native_security", nullable=False
        ),
        sa.Column("calculation_version", sa.Text(), nullable=False),
        sa.Column("universe_version", sa.Text(), nullable=True),
        sa.Column("snapshot_checksum", sa.Text(), nullable=False),
        sa.Column("source_data_version", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "exit_date IS NULL OR entry_date IS NULL OR exit_date >= entry_date",
            name=op.f("ck_forward_return_fwd_exit_after_entry"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_forward_return_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_forward_return_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forward_return")),
        sa.UniqueConstraint(
            "security_id", "as_of_date", "horizon", "snapshot_checksum", name="uq_fwd_natural"
        ),
    )
    op.create_index("ix_fwd_asof", "forward_return", ["as_of_date", "horizon"], unique=False)

    op.create_table(
        "experiment_run",
        sa.Column("experiment_run_id", sa.BigInteger(), nullable=False),
        sa.Column("experiment_id", sa.Text(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                "aborted",
                name="experiment_run_status_e",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="running",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("identity_world", _identity_world(), nullable=False),
        sa.Column("signal_version", sa.Text(), nullable=True),
        sa.Column("feature_version", sa.Text(), nullable=True),
        sa.Column("outcome_version", sa.Text(), nullable=True),
        sa.Column("universe_version", sa.Text(), nullable=True),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("snapshot_checksum", sa.Text(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=True),
        sa.Column("code_sha", sa.Text(), nullable=True),
        sa.Column("configuration_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pre_registration_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("kill_criteria_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["research_dataset_snapshot.snapshot_id"],
            name=op.f("fk_experiment_run_snapshot_id_research_dataset_snapshot"),
        ),
        sa.PrimaryKeyConstraint("experiment_run_id", name=op.f("pk_experiment_run")),
        sa.UniqueConstraint("experiment_id", "run_number", name="uq_exprun_experiment_number"),
    )
    op.create_index(
        "ix_exprun_experiment", "experiment_run", ["experiment_id", "started_at"], unique=False
    )

    op.create_table(
        "experiment_run_metric",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("experiment_run_id", sa.BigInteger(), nullable=False),
        sa.Column("metric_name", sa.Text(), nullable=False),
        sa.Column("horizon", sa.Text(), nullable=True),
        sa.Column("segment", sa.Text(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("confidence_lower", sa.Float(), nullable=True),
        sa.Column("confidence_upper", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("effective_sample_size", sa.Float(), nullable=True),
        sa.Column("calculation_version", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.experiment_run_id"],
            name=op.f("fk_experiment_run_metric_experiment_run_id_experiment_run"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_run_metric")),
    )
    op.create_index(
        "ix_exprunmetric_run",
        "experiment_run_metric",
        ["experiment_run_id", "metric_name"],
        unique=False,
    )

    op.create_table(
        "experiment_run_decision",
        sa.Column("experiment_run_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "pending",
                "promote",
                "reject",
                "hold",
                "blocked",
                name="experiment_decision_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column(
            "promotion_gate_results_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer", sa.Text(), nullable=True),
        sa.Column("knowledge_update_reference", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.experiment_run_id"],
            name=op.f("fk_experiment_run_decision_experiment_run_id_experiment_run"),
        ),
        sa.PrimaryKeyConstraint("experiment_run_id", name=op.f("pk_experiment_run_decision")),
    )

    op.create_table(
        "feature_parity_record",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("feature_name", sa.Text(), nullable=False),
        sa.Column("feature_version", sa.Text(), nullable=True),
        sa.Column("fixture_key", sa.Text(), nullable=False),
        sa.Column("legacy_value", sa.Float(), nullable=True),
        sa.Column("native_value", sa.Float(), nullable=True),
        sa.Column("absolute_difference", sa.Float(), nullable=True),
        sa.Column("tolerance", sa.Float(), server_default="0", nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("calculation_version", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_parity_record")),
    )
    op.create_index(
        "ix_fpr_feature", "feature_parity_record", ["feature_name", "passed"], unique=False
    )

    op.create_table(
        "data_divergence_record",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=True),
        sa.Column("observation_date", sa.Date(), nullable=True),
        sa.Column("feature_name", sa.Text(), nullable=True),
        sa.Column("legacy_value", sa.Float(), nullable=True),
        sa.Column("native_value", sa.Float(), nullable=True),
        sa.Column("absolute_difference", sa.Float(), nullable=True),
        sa.Column("relative_difference", sa.Float(), nullable=True),
        sa.Column(
            "divergence_class",
            sa.Enum(
                "price_adjustment",
                "dividend_treatment",
                "split_treatment",
                "delisting_inclusion",
                "ticker_history",
                "vendor_restatement",
                "missing_legacy_security",
                "universe_difference",
                "corporate_action_correction",
                "unknown",
                name="divergence_class_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("source_lineage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum(
                "unreviewed",
                "explained",
                "unexplained",
                "accepted",
                name="parity_review_status_e",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="unreviewed",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_data_divergence_record_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_divergence_record")),
    )
    op.create_index(
        "ix_ddr_review",
        "data_divergence_record",
        ["divergence_class", "review_status"],
        unique=False,
    )

    # Extend the ingestion_runs run_type CHECK to allow the Phase-2A run types
    # (raw-SQL swap; the phase1 / update_run_type precedent).
    op.execute("ALTER TABLE ingestion_runs DROP CONSTRAINT ck_ingestion_runs_run_type")
    op.execute(
        "ALTER TABLE ingestion_runs ADD CONSTRAINT ck_ingestion_runs_run_type "
        f"CHECK ({_run_type_check(_RUN_TYPES)})"
    )


def downgrade() -> None:
    # Drop dependent tables FIRST (children before parents, then any table that
    # FK-references ingestion_runs), then remove orphaned Phase-2A runs and their
    # quarantine rows, then revert the run_type check constraint.
    op.drop_table("experiment_run_decision")
    op.drop_index("ix_exprunmetric_run", table_name="experiment_run_metric")
    op.drop_table("experiment_run_metric")
    op.drop_index("ix_exprun_experiment", table_name="experiment_run")
    op.drop_table("experiment_run")
    op.drop_index("ix_ddr_review", table_name="data_divergence_record")
    op.drop_table("data_divergence_record")
    op.drop_index("ix_fpr_feature", table_name="feature_parity_record")
    op.drop_table("feature_parity_record")
    op.drop_index("ix_fwd_asof", table_name="forward_return")
    op.drop_table("forward_return")
    op.drop_table("research_dataset_snapshot")
    op.drop_table("terminal_outcome")
    op.drop_index("ix_srd_date", table_name="security_return_daily")
    op.drop_table("security_return_daily")
    op.drop_index("ix_brd_date", table_name="benchmark_return_daily")
    op.drop_table("benchmark_return_daily")
    op.drop_index("ix_sms_date", table_name="security_market_snapshot")
    op.drop_table("security_market_snapshot")
    op.drop_index("ix_spd_date", table_name="security_price_daily")
    op.drop_table("security_price_daily")
    op.drop_index("ix_ism_security", table_name="instrument_security_map")
    op.drop_index("ix_ism_instrument", table_name="instrument_security_map")
    op.drop_table("instrument_security_map")

    new_types = ", ".join(f"'{v}'" for v in _NEW_RUN_TYPES)
    op.execute(
        "DELETE FROM data_quality_issues WHERE ingestion_run_id IN "
        f"(SELECT id FROM ingestion_runs WHERE run_type IN ({new_types}))"
    )
    op.execute(f"DELETE FROM ingestion_runs WHERE run_type IN ({new_types})")
    op.execute("ALTER TABLE ingestion_runs DROP CONSTRAINT ck_ingestion_runs_run_type")
    op.execute(
        "ALTER TABLE ingestion_runs ADD CONSTRAINT ck_ingestion_runs_run_type "
        f"CHECK ({_run_type_check(_RUN_TYPES[:-5])})"
    )
