"""fundamentals and earnings layer

Revision ID: f087df9fe3e1
Revises: 4edfd3dee86a
Create Date: 2026-07-04 19:08:24.020478
"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = "f087df9fe3e1"
down_revision: str | None = "4edfd3dee86a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_fundamentals",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("market_cap", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("trailing_pe", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("forward_pe", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("price_to_book", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("trailing_eps", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("forward_eps", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("dividend_yield", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("beta", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("shares_outstanding", sa.BigInteger(), nullable=True),
        sa.Column("revenue_ttm", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("profit_margin", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("debt_to_equity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_company_fundamentals_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_company_fundamentals_instrument_id_instruments"),
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id", "as_of_date", name=op.f("pk_company_fundamentals")
        ),
    )
    op.create_table(
        "earnings_observations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("earnings_date", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_of_day", sa.Text(), nullable=True),
        sa.Column("eps_estimate", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("eps_actual", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_earnings_observations_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_earnings_observations_instrument_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_earnings_observations")),
        sa.UniqueConstraint(
            "instrument_id",
            "earnings_date",
            "observed_at",
            name=op.f("uq_earnings_observations_instrument_id_earnings_date_observed_at"),
        ),
    )
    # Current calendar: latest observation per (instrument, earnings_date).
    # Event studies read the full append-only history instead (§4.4).
    op.execute("""
        CREATE VIEW v_earnings_current AS
        SELECT DISTINCT ON (instrument_id, earnings_date)
            instrument_id, earnings_date, observed_at, time_of_day,
            eps_estimate, eps_actual, is_confirmed
        FROM earnings_observations
        ORDER BY instrument_id, earnings_date, observed_at DESC
        """)


def downgrade() -> None:
    op.execute("DROP VIEW v_earnings_current")
    op.drop_table("earnings_observations")
    op.drop_table("company_fundamentals")
