"""macro layer

Revision ID: 4edfd3dee86a
Revises: 14641b55a48c
Create Date: 2026-07-04 18:11:58.226326
"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = "4edfd3dee86a"
down_revision: str | None = "14641b55a48c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), server_default="FRED", nullable=False),
        sa.Column("provider_code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("frequency", sa.Text(), nullable=False),
        sa.Column("units", sa.Text(), nullable=True),
        sa.Column("seasonally_adjusted", sa.Boolean(), nullable=True),
        sa.Column("publication_lag_days", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_macro_series")),
        sa.UniqueConstraint(
            "provider", "provider_code", name=op.f("uq_macro_series_provider_provider_code")
        ),
    )
    op.create_table(
        "macro_observations",
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("obs_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_macro_observations_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["macro_series.id"],
            name=op.f("fk_macro_observations_series_id_macro_series"),
        ),
        sa.PrimaryKeyConstraint("series_id", "obs_date", name=op.f("pk_macro_observations")),
    )
    op.create_index("ix_macro_obs_date", "macro_observations", ["obs_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_macro_obs_date", table_name="macro_observations")
    op.drop_table("macro_observations")
    op.drop_table("macro_series")
    # ### end Alembic commands ###
