"""phase1 security master and universe integrity

Point-in-time survivorship-clean identity layer (docs/EVALUATION_FOUNDATION_
DESIGN.md, Phase 1). Adds seven tables keyed on a permanent internal
``security_id`` (never a ticker) so delisted/acquired/bankrupt/renamed/reclassed
securities persist in historical research, plus versioned universe definitions
and reconstructable point-in-time membership. Extends the ingestion_runs
run_type check to allow 'securities' and 'universe' (the update_run_type
precedent). Nothing here touches production scoring.

Note: alembic's autogenerated draft additionally proposed dropping the dynamic
feature_store_* yearly partitions (present in the DB, absent from ORM metadata
by design). Those DROPs were removed by hand; this migration is purely additive.

Revision ID: fba564e9cd38
Revises: 7c4e2a91d503
Create Date: 2026-07-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fba564e9cd38"
down_revision: str | None = "7c4e2a91d503"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_RUN_TYPES = (
    "prices",
    "macro",
    "fundamentals",
    "earnings",
    "features",
    "snapshots",
    "portfolio_import",
    "update",
    "securities",
    "universe",
)


def _run_type_check(values: tuple[str, ...]) -> str:
    return "run_type IN (" + ", ".join(f"'{v}'" for v in values) + ")"


def upgrade() -> None:
    op.create_table(
        "universe_definition",
        sa.Column("universe_definition_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "eligibility_rules_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "source_requirements_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "frozen",
                "retired",
                name="universe_status_e",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("universe_definition_id", name=op.f("pk_universe_definition")),
        sa.UniqueConstraint("name", "version", name="uq_universe_definition_name_ver"),
    )
    op.create_table(
        "security_master",
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("issuer_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "security_type",
            sa.Enum(
                "common",
                "adr",
                "etf",
                "preferred",
                "warrant",
                "right",
                "unit",
                "closed_end_fund",
                "reit",
                "other",
                name="security_type_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("share_class", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("currency", sa.Text(), server_default="USD", nullable=False),
        sa.Column("primary_exchange", sa.Text(), nullable=True),
        sa.Column("first_trade_date", sa.Date(), nullable=True),
        sa.Column("last_trade_date", sa.Date(), nullable=True),
        sa.Column("active_flag", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("delisted_flag", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("delisting_date", sa.Date(), nullable=True),
        sa.Column("delisting_reason", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_security_id", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delisting_date IS NULL OR first_trade_date IS NULL "
            "OR delisting_date >= first_trade_date",
            name=op.f("ck_security_master_delist_after_list"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_security_master_ingestion_run_id_ingestion_runs"),
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_security_master")),
        sa.UniqueConstraint("source", "source_security_id", name="uq_security_master_source_id"),
    )
    op.create_index("ix_security_master_active", "security_master", ["active_flag"], unique=False)
    op.create_table(
        "delisting_event",
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("delisting_date", sa.Date(), nullable=False),
        sa.Column("delisting_code", sa.Text(), nullable=True),
        sa.Column("delisting_reason", sa.Text(), nullable=True),
        sa.Column("delisting_return", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("cash_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("successor_security_id", sa.BigInteger(), nullable=True),
        sa.Column("terminal_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "successor_security_id IS NULL OR successor_security_id <> security_id",
            name=op.f("ck_delisting_event_delist_successor_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_delisting_event_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_delisting_event_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_delisting_event")),
    )
    op.create_table(
        "historical_classification",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("classification_scheme", sa.Text(), nullable=False),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("industry_group", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column("sub_industry", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_historical_classification_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_historical_classification_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_classification")),
        sa.UniqueConstraint(
            "security_id", "classification_scheme", "valid_from", name="uq_hist_classification"
        ),
    )
    op.create_table(
        "security_identifier_history",
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "identifier_type",
            sa.Enum(
                "ticker",
                "composite_ticker",
                "cusip",
                "isin",
                "figi",
                "vendor_id",
                name="identifier_type_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("identifier_value", sa.Text(), nullable=False),
        sa.Column("exchange", sa.Text(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_security_identifier_history_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_security_identifier_history_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint(
            "security_id",
            "identifier_type",
            "valid_from",
            name=op.f("pk_security_identifier_history"),
        ),
    )
    op.create_index(
        "ix_sec_ident_lookup",
        "security_identifier_history",
        ["identifier_type", "identifier_value"],
        unique=False,
    )
    op.create_table(
        "security_lifecycle_event",
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "listed",
                "delisted",
                "acquired",
                "merged",
                "bankrupt",
                "liquidated",
                "ticker_changed",
                "exchange_changed",
                "name_changed",
                "share_class_changed",
                "reorganized",
                "spun_off",
                name="lifecycle_event_type_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("announcement_date", sa.Date(), nullable=True),
        sa.Column("successor_security_id", sa.BigInteger(), nullable=True),
        sa.Column("predecessor_security_id", sa.BigInteger(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "successor_security_id IS NULL OR successor_security_id <> security_id",
            name=op.f("ck_security_lifecycle_event_successor_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_security_lifecycle_event_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_security_lifecycle_event_security_id_security_master"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_security_lifecycle_event")),
        sa.UniqueConstraint(
            "security_id", "event_type", "effective_date", name="uq_lifecycle_event"
        ),
    )
    op.create_table(
        "universe_membership",
        sa.Column("universe_definition_id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("membership_date", sa.Date(), nullable=False),
        sa.Column("included_flag", sa.Boolean(), nullable=False),
        sa.Column("exclusion_reason", sa.Text(), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("dollar_volume", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("exchange", sa.Text(), nullable=True),
        sa.Column(
            "security_type",
            sa.Enum(
                "common",
                "adr",
                "etf",
                "preferred",
                "warrant",
                "right",
                "unit",
                "closed_end_fund",
                "reit",
                "other",
                name="security_type_e",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("classification_id", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_universe_membership_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security_master.security_id"],
            name=op.f("fk_universe_membership_security_id_security_master"),
        ),
        sa.ForeignKeyConstraint(
            ["universe_definition_id"],
            ["universe_definition.universe_definition_id"],
            name=op.f("fk_universe_membership_universe_definition_id_universe_definition"),
        ),
        sa.PrimaryKeyConstraint(
            "universe_definition_id",
            "security_id",
            "membership_date",
            name=op.f("pk_universe_membership"),
        ),
    )
    # extend ingestion_runs.run_type via raw-SQL swap (the update_run_type precedent)
    op.execute("ALTER TABLE ingestion_runs DROP CONSTRAINT ck_ingestion_runs_run_type")
    op.execute(
        "ALTER TABLE ingestion_runs ADD CONSTRAINT ck_ingestion_runs_run_type "
        f"CHECK ({_run_type_check(_RUN_TYPES)})"
    )


def downgrade() -> None:
    # drop dependent tables FIRST (they FK-reference ingestion_runs), then remove
    # the orphaned securities/universe runs, then revert the check constraint.
    op.drop_table("universe_membership")
    op.drop_table("security_lifecycle_event")
    op.drop_index("ix_sec_ident_lookup", table_name="security_identifier_history")
    op.drop_table("security_identifier_history")
    op.drop_table("historical_classification")
    op.drop_table("delisting_event")
    op.drop_index("ix_security_master_active", table_name="security_master")
    op.drop_table("security_master")
    op.drop_table("universe_definition")
    # quarantine ledger rows (data_quality_issues) also FK-reference these runs
    op.execute(
        "DELETE FROM data_quality_issues WHERE ingestion_run_id IN "
        "(SELECT id FROM ingestion_runs WHERE run_type IN ('securities', 'universe'))"
    )
    op.execute("DELETE FROM ingestion_runs WHERE run_type IN ('securities', 'universe')")
    op.execute("ALTER TABLE ingestion_runs DROP CONSTRAINT ck_ingestion_runs_run_type")
    op.execute(
        "ALTER TABLE ingestion_runs ADD CONSTRAINT ck_ingestion_runs_run_type "
        f"CHECK ({_run_type_check(_RUN_TYPES[:-2])})"
    )
